# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "terraformlvc-june25-terraform-state"
    dynamodb_table = "terraformlvc_june25_terraform_locks"
    encrypt        = true
    key            = "stage/terraform.tfstate"
    region         = "ap-south-1"
  }
}
